### ISSUE TITLE
Private functions and Lambda expressions throw NullPointerException in StringGUI

### ISSUE THREAD

**Issue by FinnRG** [kuehnert/ITmitSchmiss-StringCommandGUI#2]
`Arrays.sort(methods)` in StringGUI fails when I try use a private function or a lambda expression in [StringBefehle.java ](https://github.com/kuehnert/ITmitSchmiss-StringCommandGUI/blob/main/StringCommandGUI/StringBefehle.java)

<details>
  <summary>
    Full Error Message
  </summary>
<pre>
<code>
  Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1246)
	at StringGUI.populateList(StringGUI.java:149)
	at StringGUI.<init>(StringGUI.java:109)
	at StringGUI.lambda$main$1(StringGUI.java:183)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
<code><pre>

</details>

**Comment by FinnRG** [comment]
Minimal Example:
```java
    public static String lambdaTest(String in) {
        ArrayList<Integer> numbers = new ArrayList<Integer>();
        numbers.add(5);
        numbers.forEach( (n) -> { System.out.println(n); } );
        return "";
    }
```
